//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PetSuppliesPlus.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class AdMonth
    {
        public AdMonth()
        {
            this.Documents = new HashSet<Document>();
            this.ExceptionReports = new HashSet<ExceptionReport>();
            this.StoreAdChoices = new HashSet<StoreAdChoice>();
            this.StoreAdChoiceHistories = new HashSet<StoreAdChoiceHistory>();
            this.Coupons = new HashSet<Coupon>();
        }
    
        public int AdMonthID { get; set; }
        public Nullable<int> AdCoupnID { get; set; }
        public Nullable<int> Year { get; set; }
        public Nullable<int> Month { get; set; }
        public Nullable<System.DateTime> LockOutEndDate { get; set; }
        public Nullable<System.DateTime> LockOutStartDate { get; set; }
        public Nullable<int> DropNumber { get; set; }
        public string PetpartnerInfo { get; set; }
        public Nullable<System.DateTime> CorpInHomeDate { get; set; }
        public Nullable<int> AdOptionID { get; set; }
        public string CorpPlanText { get; set; }
    
        public virtual ADOption ADOption { get; set; }
        public virtual Coupon Coupon { get; set; }
        public virtual ICollection<Document> Documents { get; set; }
        public virtual ICollection<ExceptionReport> ExceptionReports { get; set; }
        public virtual ICollection<StoreAdChoice> StoreAdChoices { get; set; }
        public virtual ICollection<StoreAdChoiceHistory> StoreAdChoiceHistories { get; set; }
        public virtual ICollection<Coupon> Coupons { get; set; }
    }
}
