//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PetSuppliesPlus.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ADOption
    {
        public ADOption()
        {
            this.AdMonths = new HashSet<AdMonth>();
            this.AllowedStoreOptions = new HashSet<AllowedStoreOption>();
            this.StoreAdChoices = new HashSet<StoreAdChoice>();
            this.StoreAdChoiceHistories = new HashSet<StoreAdChoiceHistory>();
        }
    
        public int ADOptionID { get; set; }
        public string ADOptionName { get; set; }
        public string SpecialChoice { get; set; }
        public string MinimumCirculation { get; set; }
        public string Vendorname { get; set; }
        public Nullable<bool> Inactive { get; set; }
    
        public virtual ICollection<AdMonth> AdMonths { get; set; }
        public virtual ICollection<AllowedStoreOption> AllowedStoreOptions { get; set; }
        public virtual ICollection<StoreAdChoice> StoreAdChoices { get; set; }
        public virtual ICollection<StoreAdChoiceHistory> StoreAdChoiceHistories { get; set; }
    }
}
