//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PetSuppliesPlus.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class AllowedStoreOption
    {
        public int AllowedStoreOptionID { get; set; }
        public Nullable<int> StoreID { get; set; }
        public Nullable<int> AdOptionID { get; set; }
    
        public virtual ADOption ADOption { get; set; }
        public virtual Store Store { get; set; }
    }
}
