//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PetSuppliesPlus.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Coupon
    {
        public Coupon()
        {
            this.AdMonths = new HashSet<AdMonth>();
            this.StoreAdChoices = new HashSet<StoreAdChoice>();
            this.StoreAdChoiceHistories = new HashSet<StoreAdChoiceHistory>();
            this.AdMonths1 = new HashSet<AdMonth>();
        }
    
        public int CouponID { get; set; }
        public string CouponText { get; set; }
        public Nullable<bool> IsActive { get; set; }
    
        public virtual ICollection<AdMonth> AdMonths { get; set; }
        public virtual ICollection<StoreAdChoice> StoreAdChoices { get; set; }
        public virtual ICollection<StoreAdChoiceHistory> StoreAdChoiceHistories { get; set; }
        public virtual ICollection<AdMonth> AdMonths1 { get; set; }
    }
}
