//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PetSuppliesPlus.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExceptionReport
    {
        public int ExceptionID { get; set; }
        public Nullable<int> MonthId { get; set; }
        public Nullable<int> StoreId { get; set; }
        public string Description { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<bool> IsAnyAdChoiseAssigned { get; set; }
    
        public virtual AdMonth AdMonth { get; set; }
        public virtual Store Store { get; set; }
    }
}
