//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PetSuppliesPlus.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public User()
        {
            this.LoginHistories = new HashSet<LoginHistory>();
            this.StoreAdChoices = new HashSet<StoreAdChoice>();
            this.StoreAdChoiceHistories = new HashSet<StoreAdChoiceHistory>();
            this.UserStores = new HashSet<UserStore>();
        }
    
        public int UserID { get; set; }
        public string Ownername { get; set; }
        public string Email { get; set; }
        public string Password { get; set; }
        public bool IsAdmin { get; set; }
        public bool IsActive { get; set; }
    
        public virtual ICollection<LoginHistory> LoginHistories { get; set; }
        public virtual ICollection<StoreAdChoice> StoreAdChoices { get; set; }
        public virtual ICollection<StoreAdChoiceHistory> StoreAdChoiceHistories { get; set; }
        public virtual ICollection<UserStore> UserStores { get; set; }
    }
}
